import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Stethoscope, Save, ArrowLeft, CheckCircle } from 'lucide-react';
import Header from '../components/Header';
import { addDoctor } from '../api/api';
import './FormPage.css';

const SPECIALIZATIONS = [
  'Cardiology','Neurology','Orthopedics','Pediatrics',
  'Oncology','Radiology','General Medicine','Surgery',
  'Dermatology','Gynecology','Psychiatry','ENT',
  'Ophthalmology','Urology','Gastroenterology',
];

export default function AddDoctor() {
  const navigate = useNavigate();
  const [form, setForm]       = useState({ doctorName: '', specialization: '' });
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError]     = useState(null);

  const handleChange = e => setForm(f => ({ ...f, [e.target.name]: e.target.value }));

  const handleSubmit = async e => {
    e.preventDefault();
    if (!form.doctorName.trim() || !form.specialization) { setError('Please fill in all fields.'); return; }
    setLoading(true); setError(null);
    try {
      await addDoctor({ doctorName: form.doctorName.trim(), specialization: form.specialization });
      setSuccess(true);
      setTimeout(() => navigate('/doctors'), 1800);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to add doctor. Check the backend.');
    } finally {
      setLoading(false);
    }
  };

  if (success) return (
    <div className="page">
      <Header title="Add Doctor" />
      <div className="page-content">
        <div className="success-screen">
          <div className="success-icon"><CheckCircle size={48} /></div>
          <h2>Doctor Added Successfully!</h2>
          <p>Redirecting to doctors list…</p>
        </div>
      </div>
    </div>
  );

  return (
    <div className="page">
      <Header title="Add Doctor" subtitle="Register a new doctor" />
      <div className="page-content">
        <button className="btn btn-secondary back-btn animate-fade-up" onClick={() => navigate('/doctors')}>
          <ArrowLeft size={14} /> Back to Doctors
        </button>
        <div className="form-layout animate-fade-up stagger-1">
          <div className="form-card">
            <div className="form-card-header">
              <div className="form-card-icon doctor-form-icon"><Stethoscope size={22} /></div>
              <div>
                <h2 className="form-card-title">New Doctor</h2>
                <p className="form-card-sub">Fill in the details below</p>
              </div>
            </div>
            {error && <div className="form-error">{error}</div>}
            <form onSubmit={handleSubmit} className="form-body">
              <div className="form-group">
                <label className="form-label">Full Name <span className="required">*</span></label>
                <input type="text" name="doctorName" className="form-input" placeholder="e.g. Anita Sharma" value={form.doctorName} onChange={handleChange} />
                <span className="form-hint">Enter full name (without Dr. prefix)</span>
              </div>
              <div className="form-group">
                <label className="form-label">Specialization <span className="required">*</span></label>
                <select name="specialization" className="form-input form-select" value={form.specialization} onChange={handleChange}>
                  <option value="">Select specialization…</option>
                  {SPECIALIZATIONS.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
              </div>
              <div className="form-actions">
                <button type="button" className="btn btn-secondary" onClick={() => navigate('/doctors')}>Cancel</button>
                <button type="submit" className="btn btn-primary" disabled={loading}>
                  {loading ? <><span className="btn-spinner" /> Saving…</> : <><Save size={14} /> Save Doctor</>}
                </button>
              </div>
            </form>
          </div>
          <div className="form-info-panel">
            <h3>Doctor Registration</h3>
            <p>Add new doctors to the hospital's medical staff. Doctor ID is auto-generated by the system.</p>
            <div className="info-tips">
              <div className="info-tip"><span className="tip-dot tip-teal" /><span>Doctor ID is auto-assigned (no need to enter)</span></div>
              <div className="info-tip"><span className="tip-dot tip-teal" /><span>Select the correct specialization from the list</span></div>
              <div className="info-tip"><span className="tip-dot tip-teal" /><span>Doctors appear in department overview on Dashboard</span></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}