import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { UserPlus, Save, ArrowLeft, CheckCircle } from 'lucide-react';
import Header from '../components/Header';
import { addPatient } from '../api/api';
import './FormPage.css';

export default function AddPatient() {
  const navigate = useNavigate();
  const [form, setForm]       = useState({ name: '', disease: '' });
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError]     = useState(null);

  const handleChange = e => setForm(f => ({ ...f, [e.target.name]: e.target.value }));

  const handleSubmit = async e => {
    e.preventDefault();
    if (!form.name.trim() || !form.disease.trim()) { setError('Please fill in all fields.'); return; }
    setLoading(true); setError(null);
    try {
      await addPatient({ name: form.name.trim(), disease: form.disease.trim() });
      setSuccess(true);
      setTimeout(() => navigate('/patients'), 1800);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to add patient. Check the backend.');
    } finally {
      setLoading(false);
    }
  };

  if (success) return (
    <div className="page">
      <Header title="Add Patient" />
      <div className="page-content">
        <div className="success-screen">
          <div className="success-icon"><CheckCircle size={48} /></div>
          <h2>Patient Added Successfully!</h2>
          <p>Redirecting to patients list…</p>
        </div>
      </div>
    </div>
  );

  return (
    <div className="page">
      <Header title="Add Patient" subtitle="Register a new patient record" />
      <div className="page-content">
        <button className="btn btn-secondary back-btn animate-fade-up" onClick={() => navigate('/patients')}>
          <ArrowLeft size={14} /> Back to Patients
        </button>
        <div className="form-layout animate-fade-up stagger-1">
          <div className="form-card">
            <div className="form-card-header">
              <div className="form-card-icon patient-form-icon"><UserPlus size={22} /></div>
              <div>
                <h2 className="form-card-title">New Patient</h2>
                <p className="form-card-sub">Fill in the details below</p>
              </div>
            </div>
            {error && <div className="form-error">{error}</div>}
            <form onSubmit={handleSubmit} className="form-body">
              <div className="form-group">
                <label className="form-label">Full Name <span className="required">*</span></label>
                <input type="text" name="name" className="form-input" placeholder="e.g. Rajesh Kumar" value={form.name} onChange={handleChange} />
              </div>
              <div className="form-group">
                <label className="form-label">Disease / Diagnosis <span className="required">*</span></label>
                <input type="text" name="disease" className="form-input" placeholder="e.g. Influenza, Diabetes, etc." value={form.disease} onChange={handleChange} />
              </div>
              <div className="form-actions">
                <button type="button" className="btn btn-secondary" onClick={() => navigate('/patients')}>Cancel</button>
                <button type="submit" className="btn btn-primary" disabled={loading}>
                  {loading ? <><span className="btn-spinner" /> Saving…</> : <><Save size={14} /> Save Patient</>}
                </button>
              </div>
            </form>
          </div>
          <div className="form-info-panel">
            <h3>Patient Registration</h3>
            <p>Register new patients to the hospital system. Patient ID is auto-generated by the system.</p>
            <div className="info-tips">
              <div className="info-tip"><span className="tip-dot" /><span>Patient ID is auto-assigned (no need to enter)</span></div>
              <div className="info-tip"><span className="tip-dot" /><span>State the primary disease or diagnosis</span></div>
              <div className="info-tip"><span className="tip-dot" /><span>Records are stored permanently in the database</span></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}