spring.datasource.url=jdbc:postgresql://dpg-d8aiiu0js32c7398i730-a.singapore-postgres.render.com:5432/hospital_db_cdwq
spring.datasource.username=hospital_db_cdwq_user
spring.datasource.password=g15WKGRsr4B8lXoNe6TcPgVOmli5d6fc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true